modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "enchantato"
version = "${version}"
displayName = "Enchantato"
authors = "TeamPotato"
description = '''
A Minecraft mod.
'''